### ISSUE TITLE
Fix infinite pagination in pagination element

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#12]
We need a way to prevent the table element from paginating indefinitely. I was thinking maybe it could do 1 query ahead of the current in terms of the page and see if the results are <10. If so it has to be the last page, if not display the next page. There is one problem with this in that it could be the last page and have 10 results (maybe the look ahead should be 11?).

Thoughts?

**Comment by alancleary** [comment]
I'd be curious to see what @sammyjava says. Our GraphQL server currently implements gene searches [via an InterMine keyword search](https://github.com/legumeinfo/graphql-server/blob/main/src/data-sources/intermine/intermine.api.js#L184). Probably the simplest thing to do would be have this return the number of results and our web component can compute how many pages there should be based on that.

This would be useful to implement in the other GraphQL endpoints based on InterMine's PathQuery API. Could something similar be done there too?

**Comment by adf-ncgr** [comment]
I'm not sure if this is what you already described, but it seems like it can be addressed by adding 1 to the page size in every request. So if the page size is 100 always ask for 101 rows and if <=100 are returned then you must be on the last page; if 101 are returned you can offer a next page (and offer the 101th row to the gods instead of the user).

**Comment by adf-ncgr** [comment]
@alancleary I agree it might be nice to know the total number of results rather than just knowing which page we're currently on and if it's the last; but giving the impression that we are a bottomless bowl of beans might have its charm too.

**Comment by alancleary** [comment]
What do people think of adding a `hasNext: boolean` attribute/property to the pagination component that would disable the next button when `false`? It's probably just a stop-gap solution, but it will give us a mechanism for preventing users from scrolling off the end of a list without forcing us  tocommit (yet) to implementing a specific way of determining pagination bounds in our APIs.

This could then be used in conjunction with Andrew's proposed page size +1 solution or whatever else makes sense for people not using the GraphQL API.

**Comment by adf-ncgr** [comment]
so I think you are basically just proposing to keep the pagination component dumb and have the logic for whether or not to display next page controlled from the smart context (which will set the boolean property)? OK by me.

**Comment by alancleary** [comment]
> so I think you are basically just proposing to keep the pagination component dumb and have the logic for whether or not to display next page controlled from the smart context (which will set the boolean property)?

Yep. The API it gets the data from will remain dumb as well. We're basically just dumping it on the API user for now...

**Comment by ctcncgr** [comment]
We have decided that the requirement for the pagination is going to be handled by the API user atm. I think this solution is good.

If we want to revisit this we can go with the 'result.length + 1' as a solution to perform a check for the next page.

**Comment by alancleary** [comment]
Reopening since the solution requires adding a `hasNext` property to the pagination element, which hasn't been implemented yet.

**Comment by alancleary** [comment]
I'm going to go ahead and implement this.

**Comment by alancleary** [comment]
A `hasNext` boolean property was added to the pagination component in commit d5838f0fac07a7419f04ed70244e9a41f1bb6ea6. Setting the property to false disables the pagination component's next button (it's false by default). This commit also added code that automatically disables the previous button when the `page` property is not greater than 1.

**Comment by alancleary** [comment]
Support for the pagination element's new `hasNext` property was added to the paginated search mixin in commit 9a8fe095a37953fdde870172527b81fa2001c58a. This didn't require any changes to the gene search or trait search components, but it changed the signature of the search functions they consume since they use the mixin. See their respective examples in the `dev/` directory for the updated syntax.

The question now is do we want to make the `hasNext` property optional in the search result object returned by a search function? If omitted, we could assume that there is a next page. This would then allow people to scroll off the end and the paginated search mixin could catch this by noticing that the list of results is actually empty and disable the next button. This would support API users that don't want to (or possibly can't?!) compute the `hasNext` value.

**Comment by adf-ncgr** [comment]
not that it's my call, but I think having hasNext be optional would be good.
All mortals are, in some sense, unable to specify the value of this...

**Comment by alancleary** [comment]
The `hasNext` search result attribute was made optional in commit 56677be5d611efcb7d1f205ce6f5566fd47b28ad. If no value is provided, users can page off the end of a set of results, but only by one page because the paginated search mixin will disable the next button if a search result object has no results.

**Comment by alancleary** [comment]
Mechanisms for preventing infinite pagination when using the paginated search mixin were are in PR #26. Closing.

**Comment by svengato** [comment]
In the examples (dev/lis-[gene|trait]-search.html), shouldn't line 54 test for hasNext, like
```
  if (hasNext) data.geneSearch.pop();
```
? Otherwise it always removes the last gene or trait in the list.

**Comment by alancleary** [comment]
> In the examples (dev/lis-[gene|trait]-search.html), shouldn't line 54 test for hasNext, like
> 
> ```
>   if (hasNext) data.geneSearch.pop();
> ```
> 
> ? Otherwise it always removes the last gene or trait in the list.

Good catch! Mind making a PR with the fix?

**Comment by svengato** [comment]
Sure, stay tuned -

**Comment by svengato** [comment]
Done.
