### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by That-Thing** [legumeinfo/web-components#307]
Since modifiable example text was added, a new release would be nice since the functionality was requested for SoyBase.

**Comment by adf-ncgr** [comment]
@That-Thing, how much is this holding you up? @alancleary is off this week for the holidays, but someone else could probably manage to make a release in his absence if needed (I think there's a checklist of steps somewhere we can crib from). Since he has been threatening to train others on the team to do the releases, I'm tempted to wait until he's back so he can make sure we're fully understanding the process; but if you need it sooner let me know and we can bumble our way forward.

**Comment by That-Thing** [comment]
Waiting should be fine since the feature in SoyBase this is needed for isn't even in main yet.

**Comment by adf-ncgr** [comment]
Great, thanks for your patience with our official process (which grinds slowly, but exceedingly fine...)

**Comment by alancleary** [comment]
In progress. See issue #313.
