### ISSUE TITLE
pagination issues

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/web-components#40]
- the top of the result list shows "10 results found" regardless of how many results>10 are actually found
- the paging section at the bottom shows only Page 1 regardless of how many pages>1 there actually are

**Comment by alancleary** [comment]
> the top of the result list shows "10 results found" regardless of how many results>10 are actually found

This is correct. It's the number of results loaded for that particular page. We can change the text to better convey that or update the code to support a result total as well.

> the paging section at the bottom shows only Page 1 regardless of how many pages>1 there actually are

This is also by design. It was simpler to implement "bottomless" paging rather than requiring web component users to provide a bunch of paging info that may or may not be trivial to come up with.

In general, I think adding support for "bounded" paging is good, but the "bottomless" functionality should be the default in case users can't provide the information necessary for the bounded UI elements.

**Comment by sammyjava** [comment]
Well both of these "correct" features are counter to normal user experience. Users are accustomed to seeing the total number of results reported at the top, and a list of pages at the bottom. But I'll not impose UI requirements on our apps, leaving that to the focus groups that we'll surely employ during beta testing. :)
